[build]
  # Build command - use netlify-specific build script
  command = "npm run build:netlify"
  
  # Publish directory - where Next.js builds the site
  publish = "gui/gui/.next"

# Use Netlify's Next.js plugin for seamless deployment
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Netlify build environment variables
  NODE_ENV = "production"
  NODE_VERSION = "18"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"