[build]
  # Base directory for Next.js app
  base = "gui/gui"
  
  # Build command with debugging and error handling - ensure node_modules exists before plugin runs
  command = "echo 'Starting build...' && npm --version && node --version && npm install && echo 'Dependencies installed, building...' && npm run build && echo 'Build completed successfully' && ls -la node_modules"

# Netlify will auto-detect Next.js and use the appropriate plugin version

[build.environment]
  # Netlify build environment variables
  NODE_ENV = "production"
  NODE_VERSION = "22"
  # Disable Next.js telemetry that might cause issues
  NEXT_TELEMETRY_DISABLED = "1"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"